// <auto-generated />
namespace SBD.GL.Module.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class three1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(three1));
        
        string IMigrationMetadata.Id
        {
            get { return "201901100103446_three1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
