// <auto-generated />
namespace SBD.GL.Module.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _ref : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_ref));
        
        string IMigrationMetadata.Id
        {
            get { return "201901100107092_ref"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
